# Generated by Django 5.0.1 on 2024-03-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='description',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='category',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='location',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='type_of_lesson',
            field=models.BooleanField(default=None),
        ),
    ]
