# Generated by Django 5.0.1 on 2024-02-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('tutor', 'Tutor'), ('student', 'Student')], max_length=20),
        ),
    ]
