# Generated by Django 5.0.1 on 2024-02-08 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role_alter_customuser_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='Roles',
        ),
    ]
